OCP4: Add reponse for SI-12
ComplianceAsCode/redhat pull request #1291
Opened 2021-05-12 08:15 UTC by JAORMX

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

2021-05-12 08:17 UTC, JAORMX commented
Pull-request updated, HEAD is now 041db8d8907759083121dc884ff3b89bc8ed27f8

2021-05-12 16:53 UTC, carlosmmatos requested changes

2021-05-12 16:53 UTC, carlosmmatos commented on openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> +        o the aforementioned data shall be ensured and determined by the customer.
```suggestion
        of the aforementioned data shall be ensured and determined by the customer.
```

2021-05-12 16:53 UTC, carlosmmatos commented on openshift-container-platform-4/policies/SI-System_and_Information_Integrity/component.yaml
> +        o the aforementioned data shall be ensured and determined by the customer.
I think this is supposed to be `of` right?

2021-05-14 16:59 UTC, carlosmmatos approved these changes

2021-05-14 16:59 UTC, merged