OCP4: Add response for CM-5(3)
ComplianceAsCode/redhat pull request #1296
Opened 2021-05-12 11:41 UTC by JAORMX

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

2021-05-14 17:21 UTC, carlosmmatos requested changes
I would try to re-word this a little and talk more about what we do for not just the containers that run on the platform.. but what about how OpenShift get's it's updates? RHCOS - gpgkey, yatti yatti..

Does that make sense?

2021-05-17 06:06 UTC, JAORMX commented
> I would try to re-word this a little and talk more about what we do for not just the containers that run on the platform.. but what about how OpenShift get's it's updates?

Makes sense, let me try to find docs about this.

> RHCOS - gpgkey, yatti yatti..

@carlosmmatos let's handle RHCOS responses in the `coreos-4` section.
> 
> Does that make sense?

2021-05-17 12:43 UTC, carlosmmatos approved these changes

2021-05-17 12:43 UTC, carlosmmatos commented
@JAORMX that's fine.

2021-05-17 12:43 UTC, merged